/** Names accepted for Category.icon — must match the keys of CATEGORY_ICONS in components/icons/category-icon.tsx. */
export const CATEGORY_ICON_NAMES = [
  "Layers",
  "Armchair",
  "Sofa",
  "SprayCan",
  "Sparkles",
  "Droplets",
  "BrushCleaning",
  "Car",
  "CarFront",
  "Zap",
  "Plug",
  "Lightbulb",
  "Bike",
  "Wind",
  "Fan",
  "Gauge",
  "CircleDot",
  "Wrench",
  "Box",
  "Package",
  "BadgeCheck",
  "LayoutGrid",
] as const;
